compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

httpProxy: "${http_proxy:-}"

httpsProxy: "${https_proxy:-}"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.0.cjs
